name: Setup EdgeDriver and Run Tests

on:
  push:
    branches:
      - main  # Adjust to your desired branch
  pull_request:
    branches:
      - main  # Adjust to your desired branch

jobs:
  setup_and_test:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Microsoft Edge
      - name: Install Microsoft Edge
        run: |
          choco install microsoft-edge --version=118.0.2088.81 --ignore-checksums

      # Step 3: Set up EdgeDriver
      - name: Setup EdgeDriver
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"  # Halt on errors for debugging
          
          try {
              # Get the installed Microsoft Edge version
              $edgeVersion = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Edge\BLBeacon").version
              Write-Host "Installed Microsoft Edge version: $edgeVersion"

              # Parse the major version number
              $edgeMajorVersion = $edgeVersion.Split('.')[0]
              Write-Host "Edge major version: $edgeMajorVersion"

              # Fetch the corresponding EdgeDriver version
              $edgeDriverUrl = "https://msedgedriver.azureedge.net/$edgeVersion/edgedriver_win64.zip"
              Write-Host "Downloading EdgeDriver from: $edgeDriverUrl"
              
              # Download EdgeDriver
              Invoke-WebRequest -Uri $edgeDriverUrl -OutFile "edgedriver.zip"
          } catch {
              Write-Host "Failed to get the corresponding EdgeDriver version. Error details: $_"
              exit 1
          }

          # Unzip and install EdgeDriver
          Write-Host "Extracting EdgeDriver..."
          Expand-Archive edgedriver.zip -DestinationPath .
          Copy-Item msedgedriver.exe C:\Windows\System32  # Make EdgeDriver globally accessible
          Write-Host "EdgeDriver installed successfully."

      # Step 4: Verify EdgeDriver installation
      - name: Verify EdgeDriver Installation
        run: msedgedriver --version

      # Step 5: Set up Java and Maven
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Step 6: Run Maven tests
      - name: Run Tests
        run: |
          mvn clean test -Ddataproviderthreadcount=3 -Dcucumber.filter.tags=@Regression
