name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      selectedTag:
        description: "Select the tag to filter tests"
        required: true
        default: "@Smoke"
        type: choice
        options:
          - "@Smoke"
          - "@Regression"
          - "@BestSeller"
          - "@ShoppingToCart"
          - "@Sanity"
          - "@E2E"

jobs:
  build:
    runs-on: Demo

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn clean test -D"dataproviderthreadcount"="3" -D"cucumber.filter.tags"="${{ inputs.selectedTag }}"

  archive-test-results:
    needs: build
    runs-on: Demo
    steps:
    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: ./target/cucumber-reports
